production:
  clients:
    default:
      database: ba689883bsx7ngb
      hosts:
        - ba689883bsx7ngb-mongodb.services.clever-cloud.com:27017
      options:
        user: 'uvurvoiunysqafv0mvht'
        password: 'kMlkP3Ko4mvxuPVD5pur'
development:
  clients:
    default:
      database: ba689883bsx7ngb
      hosts:
        - ba689883bsx7ngb-mongodb.services.clever-cloud.com:27017
      options:
        user: 'uvurvoiunysqafv0mvht'
        password: 'kMlkP3Ko4mvxuPVD5pur'
test:
  clients:
    default:
      database: ba689883bsx7ngb
      hosts:
        - ba689883bsx7ngb-mongodb.services.clever-cloud.com:27017
      options:
        user: 'uvurvoiunysqafv0mvht'
        password: 'kMlkP3Ko4mvxuPVD5pur'
